modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="neomod"
version="1.0.0"
displayName="NeoMod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="redre, MCreator"

[[dependencies.neomod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



